version: "3.9"
services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /var/postgres:/var/lib/postgresql/data
    networks:
      - wanrun
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 2s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wanrun
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      GO_ENV: ${GO_ENV}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/var/run
    networks:
      - wanrun
networks: 
  wanrun:
# データの永続化
volumes:
  postgres:
  backend:
