version: "3.9"
services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /var/postgres:/var/lib/postgresql/data
    networks:
      wanrun:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wanrun
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
networks: 
  wanrun:
# データの永続化
volumes:
  postgres:
  backend:
